const ROOM_NAME_MAX_CHARACTERS = 50;
const ROOM_MAX_DURATION = 43800; // minutes in a month
const ROOM_DEFAULT_MAX_CONNECTIONS = 4;
const ROOM_MAX_CONNECTIONS_ALLOWED = 16;
module.exports = {
	ROOM_NAME_MAX_CHARACTERS,
	ROOM_MAX_DURATION,
	ROOM_DEFAULT_MAX_CONNECTIONS,
	ROOM_MAX_CONNECTIONS_ALLOWED,
};
