version: "3.8"
services:
    bot:
        build: ./src
        container_name: chat_server
        ports:
            - 80:80
        volumes:
            - ./src/:/app
            - /app/node_modules
            - /var/run/docker.sock:/var/run/docker.sock
        env_file:
            - ./env/app.env
