const CODE_BAD_REQUEST = 400;
const CODE_UNAUTHORIZED = 401;
const CODE_FORBIDDEN_RESOURCE = 403;
const CODE_NOT_FOUND = 404;
const CODE_OK = 200;

module.exports = {
	CODE_BAD_REQUEST,
	CODE_UNAUTHORIZED,
	CODE_FORBIDDEN_RESOURCE,
	CODE_NOT_FOUND,
	CODE_OK,
};
